controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

service_blob:
    path: /service.blob
    controller: App\Controller\ServiceController::blob
